apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: keystone-manager
    version: v0.1.0
  name: keystone-manager
  namespace: os-keystone
spec:
  template:
    metadata:
      labels:
        openstack-app: keystone-manager
        version: v0.1.0
      name: keystone-manager
      namespace: os-keystone
    spec:
      hostNetwork: true
      nodeSelector:
        openstack-keystone: 'true'
      containers:
        - name: keystone-manager
          image: {{ IMAGE_KEYSTONE_MANAGER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: OS_MARINA_SERVICE
              value: keystone
          volumeMounts:
            - name: os-config
              mountPath: /run/secrets/config
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config
          secret:
            secretName: keystone-manager
# ---
# apiVersion: v1
# kind: ReplicationController
# metadata:
#   labels:
#     openstack-app: keystone
#     version: v0.1.0
#   name: keystone
#   namespace: os-keystone
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         openstack-app: keystone
#         version: v0.1.0
#       name: keystone
#       namespace: os-keystone
#     spec:
#       nodeSelector:
#         openstack-keystone: 'true'
#         arch: 'x86'
#       containers:
#         - name: keystone-api
#           image: docker.io/port/keystone-api:latest
#           imagePullPolicy: Always
#           ports:
#           - containerPort: 5000
#             name: api
#             protocol: TCP
#           - containerPort: 35357
#             name: admin
#             protocol: TCP
#           env:
#             - name: OS_DOMAIN
#               value: {{ OS_DOMAIN }}
#           volumeMounts:
#             - name: os-config
#               mountPath: "/etc/os-config"
#               readOnly: true
#             - name: os-ssl-database
#               mountPath: '/etc/os-ssl-database'
#               readOnly: true
#             - name: os-ssl
#               mountPath: "/etc/os-ssl"
#               readOnly: true
#             - name: os-websso
#               mountPath: "/etc/os-websso"
#               readOnly: true
#             - name: os-fernet
#               mountPath: "/etc/os-fernet"
#               readOnly: true
#             - name: ipa-ca-crt
#               mountPath: /etc/pki/tls/certs/ca-bundle.crt
#               readOnly: true
#           securityContext:
#             privileged: false
#       volumes:
#         - name: os-config
#           secret:
#             secretName: keystone
#         - name: os-ssl-database
#           hostPath:
#             path: /etc/harbor/auth/host/database
#         - name: os-ssl
#           secret:
#             secretName: keystone-ssl-secret
#         - name: os-websso
#           secret:
#             secretName: keystone-websso-secret
#         - name: os-fernet
#           secret:
#             secretName: keystone-fernet-secret
#         - name: ipa-ca-crt
#           hostPath:
#             path: /etc/ipa/ca.crt
# ---
# apiVersion: v1
# kind: ReplicationController
# metadata:
#   labels:
#     openstack-app: keystone-v2
#     version: v0.1.0
#   name: keystone-v2
#   namespace: os-keystone
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         openstack-app: keystone-v2
#         version: v0.1.0
#       name: keystone-v2
#       namespace: os-keystone
#     spec:
#       nodeSelector:
#         openstack-keystone: 'true'
#         arch: 'x86'
#       containers:
#         - name: keystone-v2
#           image: docker.io/port/keystone-default:latest
#           imagePullPolicy: Always
#           ports:
#           - containerPort: 5001
#             name: api
#             protocol: TCP
#           - containerPort: 35358
#             name: admin
#           env:
#             - name: OS_DOMAIN
#               value: {{ OS_DOMAIN }}
#           volumeMounts:
#             - name: os-config
#               mountPath: "/etc/os-config"
#               readOnly: true
#             - name: os-ssl-database
#               mountPath: '/etc/os-ssl-database'
#               readOnly: true
#             - name: os-ssl
#               mountPath: "/etc/os-ssl"
#               readOnly: true
#             - name: os-websso
#               mountPath: "/etc/os-websso"
#               readOnly: true
#             - name: os-fernet
#               mountPath: "/etc/os-fernet"
#               readOnly: true
#             - name: ipa-ca-crt
#               mountPath: /etc/pki/tls/certs/ca-bundle.crt
#               readOnly: true
#           securityContext:
#             privileged: false
#       volumes:
#         - name: os-config
#           secret:
#             secretName: keystone-v2
#         - name: os-ssl-database
#           hostPath:
#             path: /etc/harbor/auth/host/database
#         - name: os-ssl
#           secret:
#             secretName: keystone-v2-ssl-secret
#         - name: os-websso
#           secret:
#             secretName: keystone-websso-secret
#         - name: os-fernet
#           secret:
#             secretName: keystone-fernet-secret
#         - name: ipa-ca-crt
#           hostPath:
#             path: /etc/ipa/ca.crt
