kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    openstack-app: keystone-db
  name: os-keystone-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/harbor/keystone/mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    openstack-app: keystone-db
  name: os-keystone-db
  namespace: os-keystone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: keystone-manager
    version: v0.1.0
  name: keystone-manager
  namespace: os-keystone
spec:
  template:
    metadata:
      labels:
        openstack-app: keystone-manager
        version: v0.1.0
      name: keystone-manager
      namespace: os-keystone
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: keystone-manager
          image: {{ IMAGE_KEYSTONE_MANAGER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: os-config-kubecfg
              mountPath: /var/run/harbor/secrets/config-kubecfg
              readOnly: true
            - name: os-config-user-ipa
              mountPath: /var/run/harbor/secrets/config-user-ipa
              readOnly: true
            - name: os-config-host-ipa
              mountPath: /var/run/harbor/secrets/config-host-ipa
              readOnly: true
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-ldap
              mountPath: /var/run/harbor/secrets/config-ldap
              readOnly: true
            - name: os-config-user
              mountPath: /var/run/harbor/secrets/config-user
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config-kubecfg
          secret:
            secretName: keystone-kubecfg
        - name: os-config-user-ipa
          secret:
            secretName: keystone-user-ipa
        - name: os-config-host-ipa
          secret:
            secretName: keystone-host-ipa
        - name: os-config-db-root
          secret:
            secretName: keystone-db-root
        - name: os-config-db
          secret:
            secretName: keystone-db
        - name: os-config-ldap
          secret:
            secretName: keystone-ldap
        - name: os-config-user
          secret:
            secretName: keystone-user
        - name: os-config-ssl-secret
          secret:
            secretName: keystone-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: keystone-user-ssl-secret
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: keystone-bootstraper
    version: v0.1.0
  name: keystone-bootstraper
  namespace: os-keystone
spec:
  template:
    metadata:
      labels:
        openstack-app: keystone-bootstraper
        version: v0.1.0
      name: keystone-bootstraper
      namespace: os-keystone
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: keystone-bootstraper
          image: {{ IMAGE_KEYSTONE_MANAGER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: OS_MANAGEMENT_ACTION
              value: bootstrap
          volumeMounts:
            - name: os-config-kubecfg
              mountPath: /var/run/harbor/secrets/config-kubecfg
              readOnly: true
            - name: os-config-user-ipa
              mountPath: /var/run/harbor/secrets/config-user-ipa
              readOnly: true
            - name: os-config-host-ipa
              mountPath: /var/run/harbor/secrets/config-host-ipa
              readOnly: true
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-ldap
              mountPath: /var/run/harbor/secrets/config-ldap
              readOnly: true
            - name: os-config-user
              mountPath: /var/run/harbor/secrets/config-user
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config-kubecfg
          secret:
            secretName: keystone-kubecfg
        - name: os-config-user-ipa
          secret:
            secretName: keystone-user-ipa
        - name: os-config-host-ipa
          secret:
            secretName: keystone-host-ipa
        - name: os-config-db-root
          secret:
            secretName: keystone-db-root
        - name: os-config-db
          secret:
            secretName: keystone-db
        - name: os-config-ldap
          secret:
            secretName: keystone-ldap
        - name: os-config-user
          secret:
            secretName: keystone-user
        - name: os-config-ssl-secret
          secret:
            secretName: keystone-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: keystone-user-ssl-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: keystone-db
    version: v0.1.0
  name: keystone-db
  namespace: os-keystone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: keystone-db
        version: v0.1.0
      name: keystone-db
      namespace: os-keystone
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: keystone-db
          image: {{ IMAGE_MARIADB_SERVER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: 3307
              hostPort: 3307
              protocol: TCP
              name: mysql
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: DB_PORT
              value: '3307'
            - name: DB_TLS
              value: /run/harbor/auth/db
            - name: DB_ROOT_PASSWORD
              value: AUTH_KEYSTONE_DB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: AUTH_KEYSTONE_MARIADB_DATABASE
            - name: MARIADB_USER
              value: AUTH_KEYSTONE_MARIADB_USER
            - name: MARIADB_PASSWORD
              value: AUTH_KEYSTONE_MARIADB_PASSWORD
            - name: DB_NAME
              value: AUTH_KEYSTONE_DB_NAME
            - name: DB_USER
              value: AUTH_KEYSTONE_DB_USER
            - name: DB_PASSWORD
              value: AUTH_KEYSTONE_DB_PASSWORD
          volumeMounts:
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-db-ssl-secret
              mountPath: /run/harbor/auth/db
              readOnly: true
            - mountPath: /var/lib/mysql
              name: os-keystone-db
              readOnly: false
      volumes:
        - name: os-config-db-root
          secret:
            secretName: keystone-db-root
        - name: os-config-db
          secret:
            secretName: keystone-db
        - name: os-config-db-ssl-secret
          secret:
            secretName: keystone-db-ssl-secret
        - name: os-keystone-db
          persistentVolumeClaim:
            claimName: os-keystone-db
----
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: keystone
    version: v0.1.0
  name: keystone-api-master
  namespace: os-keystone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: keystone
        version: v0.1.0
      name: keystone-api-master
      namespace: os-keystone
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: keystone-api
          image: {{ IMAGE_KEYSTONE_API }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
              name: k-api
            - containerPort: 35357
              hostPort: 35357
              protocol: TCP
              name: k-admin
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: os-config-host-ipa
              mountPath: /var/run/harbor/secrets/config-host-ipa
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-ldap
              mountPath: /var/run/harbor/secrets/config-ldap
              readOnly: true
            - name: os-config-user
              mountPath: /var/run/harbor/secrets/config-user
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
            - name: os-config-federation-saml2-secret
              mountPath: /run/harbor/auth/saml2
              readOnly: true
          securityContext:
            privileged: false
      volumes:
        - name: os-config-host-ipa
          secret:
            secretName: keystone-host-ipa
        - name: os-config-db
          secret:
            secretName: keystone-db
        - name: os-config-ldap
          secret:
            secretName: keystone-ldap
        - name: os-config-user
          secret:
            secretName: keystone-user
        - name: os-config-ssl-secret
          secret:
            secretName: keystone-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: keystone-user-ssl-secret
        - name: os-config-federation-saml2-secret
          secret:
            secretName: keystone-federation-saml2-secret
