apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    openstack-app: ingress-loadbalancer
    version: v0.1.0
  name: ingress-loadbalancer-conf
  namespace: os-loadbalancer
data:
  server-name-hash-bucket-size: "128"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    openstack-app: ingress-loadbalancer
    version: v0.1.0
  name: ingress-loadbalancer
  namespace: os-loadbalancer
spec:
  template:
    metadata:
      labels:
        openstack-app: ingress-loadbalancer
        version: v0.1.0
      name: ingress-loadbalancer
      namespace: os-loadbalancer
    spec:
      hostNetwork: true
      containers:
      - name: ingress-loadbalancer
        image: {{ IMAGE_LOADBALANCER_INGRESS }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        ports:
          - containerPort: 80
            hostPort: 80
            protocol: TCP
            name: http
          - containerPort: 443
            hostPort: 443
            protocol: TCP
            name: https
          - containerPort: 6643
            hostPort: 6643
            protocol: TCP
            name: ovs-db
        env:
          - name: OS_DOMAIN
            value: {{ OS_DOMAIN }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NGINX_CONFIGMAP
            value: ingress-loadbalancer-conf
        volumeMounts:
          - name: os-config-kubecfg
            mountPath: /var/run/harbor/secrets/config-kubecfg
            readOnly: true
          - name: os-config-ssl-secret
            mountPath: /run/harbor/auth/ssl
            readOnly: true
          - name: os-config-ssl-user-secret
            mountPath: /run/harbor/auth/user
            readOnly: true
        securityContext:
          privileged: false
      volumes:
        - name: os-config-kubecfg
          secret:
            secretName: loadbalancer-kubecfg
        - name: os-config-ssl-secret
          secret:
            secretName: loadbalancer-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: loadbalancer-user-ssl-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: error-page-server
    version: v0.1.0
  name: error-page-server
  namespace: os-loadbalancer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: error-page-server
        version: v0.1.0
      name: error-page-server
      namespace: os-loadbalancer
    spec:
      hostNetwork: true
      containers:
      - name: error-page-server
        image: {{ IMAGE_LOADBALANCER_ERROR_SERVER }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
          - name: OS_DOMAIN
            value: {{ OS_DOMAIN }}
          - name: PORT
            value: '81'
        ports:
          - containerPort: 81
            hostPort: 81
            protocol: TCP
            name: http
