# Additional secrets required by this namespace:
# loadbalancer-ssl-secret - from marina service manager
# loadbalancer-user-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: loadbalancer-kubecfg
  namespace: os-loadbalancer
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
