# kuryr-user-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: kuryr-keystone
  namespace: kube-system
type: Opaque
data:
  kuryr-keystone-user: {{ AUTH_KURYR_KEYSTONE_USER }}
  kuryr-keystone-password: {{ AUTH_KURYR_KEYSTONE_PASSWORD }}
