# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# neutron-ssl-secret - from marina service manager
# neutron-user-ssl-secret - from marina service manager
# neutron-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: neutron-kubecfg
  namespace: os-neutron
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-user-ipa
  namespace: os-neutron
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-host-ipa
  namespace: os-neutron
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-db-root
  namespace: os-neutron
type: Opaque
data:
  mariadb-root-password: {{ AUTH_NEUTRON_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-db
  namespace: os-neutron
type: Opaque
data:
  mariadb-test-database: {{ AUTH_NEUTRON_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_NEUTRON_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_NEUTRON_MARIADB_PASSWORD }}
  neutron-db-name: {{ AUTH_NEUTRON_DB_NAME }}
  neutron-db-user: {{ AUTH_NEUTRON_DB_USER }}
  neutron-db-password: {{ AUTH_NEUTRON_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-keystone
  namespace: os-neutron
type: Opaque
data:
  neutron-keystone-user: {{ AUTH_NEUTRON_KEYSTONE_USER }}
  neutron-keystone-password: {{ AUTH_NEUTRON_KEYSTONE_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-shared-secret
  namespace: os-neutron
type: Opaque
data:
  neutron-shared-secret: {{ AUTH_NEUTRON_SHARED_SECRET }}
---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-shared-secret
  namespace: os-nova
type: Opaque
data:
  neutron-shared-secret: {{ AUTH_NEUTRON_SHARED_SECRET }}
