apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: neutron-db
  name: neutron-db
  namespace: os-neutron
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    openstack-app: neutron-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: neutron
  name: neutron
  namespace: os-neutron
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 9696
    protocol: TCP
    targetPort: 9696
  selector:
    openstack-app: neutron
