# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# cinder-ssl-secret - from marina service manager
# cinder-user-ssl-secret - from marina service manager
# cinder-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: cinder-kubecfg
  namespace: os-cinder
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cinder-user-ipa
  namespace: os-cinder
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cinder-host-ipa
  namespace: os-cinder
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cinder-db-root
  namespace: os-cinder
type: Opaque
data:
  mariadb-root-password: {{ AUTH_CINDER_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cinder-db
  namespace: os-cinder
type: Opaque
data:
  mariadb-test-database: {{ AUTH_CINDER_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_CINDER_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_CINDER_MARIADB_PASSWORD }}
  cinder-db-name: {{ AUTH_CINDER_DB_NAME }}
  cinder-db-user: {{ AUTH_CINDER_DB_USER }}
  cinder-db-password: {{ AUTH_CINDER_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cinder-keystone
  namespace: os-cinder
type: Opaque
data:
  cinder-keystone-user: {{ AUTH_CINDER_KEYSTONE_USER }}
  cinder-keystone-password: {{ AUTH_CINDER_KEYSTONE_PASSWORD }}
