# Additional secrets required by this namespace:
# murano-ssl-secret - from marina service manager
# murano-user-ssl-secret - from marina service manager
# murano-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: murano-kubecfg
  namespace: os-murano
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: murano-user-ipa
  namespace: os-murano
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: murano-host-ipa
  namespace: os-murano
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: murano-db-root
  namespace: os-murano
type: Opaque
data:
  mariadb-root-password: {{ AUTH_MURANO_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: murano-db
  namespace: os-murano
type: Opaque
data:
  mariadb-test-database: {{ AUTH_MURANO_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_MURANO_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_MURANO_MARIADB_PASSWORD }}
  murano-db-name: {{ AUTH_MURANO_DB_NAME }}
  murano-db-user: {{ AUTH_MURANO_DB_USER }}
  murano-db-password: {{ AUTH_MURANO_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: murano-keystone
  namespace: os-murano
type: Opaque
data:
  murano-keystone-user: {{ AUTH_MURANO_KEYSTONE_USER }}
  murano-keystone-password: {{ AUTH_MURANO_KEYSTONE_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: messaging-auth
  namespace: os-murano
type: Opaque
data:
  auth-messaging-user: {{ AUTH_MURANO_RABBITMQ_USER }}
  auth-messaging-pass: {{ AUTH_MURANO_RABBITMQ_PASS }}
