# Additional secrets required by this namespace:
# etcd-ssl-secret - from marina service manager
# ectd-user-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: etcd-kubecfg
  namespace: os-etcd
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
