apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: etcd-master
  name: etcd
  namespace: os-etcd
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP
    name: etcd
  - port: 7001
    targetPort: 7001
    protocol: TCP
    name: etcd-peers
  selector:
    openstack-app: etcd-master
