# Additional secrets required by this namespace:
# memcached-ssl-secret - from marina service manager
# memcached-user-ssl-secret - from marina service manager
# memcached-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: memcached-kubecfg
  namespace: os-memcached
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: memcached-user-ipa
  namespace: os-memcached
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: memcached-host-ipa
  namespace: os-memcached
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
