# Additional secrets required by this namespace:
# memcached-ssl-secret - from marina service manager
# memcached-user-ssl-secret - from marina service manager
# memcached-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: memcached-kubecfg
  namespace: os-memcached
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
