apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    openstack-app: glance
    version: v0.1.0
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/rewrite-target: /
  name: glance
  namespace: os-glance
spec:
  tls:
    - hosts:
        - glance.harboros.net
      secretName: glance-ssl-secret
    - hosts:
        - glance.os-glance.svc.harboros.net
      secretName: glance-ssl-secret
  rules:
  - host: glance.harboros.net
    http:
      paths:
      - path: /
        backend:
          serviceName: glance
          servicePort: 9292
  - host: glance.os-glance.svc.harboros.net
    http:
      paths:
      - path: /
        backend:
          serviceName: glance
          servicePort: 9292
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    openstack-app: glance-reg
    version: v0.1.0
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/rewrite-target: /
  name: glance-registry
  namespace: os-glance
spec:
  tls:
    - hosts:
        - glance-registry.harboros.net
      secretName: glance-registry-ssl-secret
    - hosts:
        - glance-registry.os-glance.svc.harboros.net
      secretName: glance-registry-ssl-secret
  rules:
  - host: glance-registry.harboros.net
    http:
      paths:
      - path: /
        backend:
          serviceName: glance-registry
          servicePort: 9191
  - host: glance-registry.os-glance.svc.harboros.net
    http:
      paths:
      - path: /
        backend:
          serviceName: glance-registry
          servicePort: 9191
