apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    openstack-app: portal
    version: v0.1.0
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/rewrite-target: /
  name: portal
  namespace: os-portal
spec:
  tls:
    - hosts:
        - portal.{{ OS_DOMAIN }}
      secretName: portal-ssl-secret
    - hosts:
        - portal.os-portal.svc.{{ OS_DOMAIN }}
      secretName: portal-ssl-secret
  rules:
  - host: portal.{{ OS_DOMAIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: portal
          servicePort: 4434
  - host: portal.os-portal.svc.{{ OS_DOMAIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: portal
          servicePort: 4434
