# raven-user-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: raven-kubecfg
  namespace: os-raven
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: raven-user-ipa
  namespace: os-raven
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: raven-host-ipa
  namespace: os-raven
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: raven-keystone
  namespace: os-raven
type: Opaque
data:
  raven-keystone-user: {{ AUTH_RAVEN_KEYSTONE_USER }}
  raven-keystone-password: {{ AUTH_RAVEN_KEYSTONE_PASSWORD }}
