# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# glance-ssl-secret - from marina service manager
# glance-registry-ssl-secret - from marina service manager
# glance-user-ssl-secret - from marina service manager
# glance-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: glance-kubecfg
  namespace: os-glance
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: glance-user-ipa
  namespace: os-glance
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: glance-host-ipa
  namespace: os-glance
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: glance-db-root
  namespace: os-glance
type: Opaque
data:
  mariadb-root-password: {{ AUTH_GLANCE_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: glance-db
  namespace: os-glance
type: Opaque
data:
  mariadb-test-database: {{ AUTH_GLANCE_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_GLANCE_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_GLANCE_MARIADB_PASSWORD }}
  glance-db-name: {{ AUTH_GLANCE_DB_NAME }}
  glance-db-user: {{ AUTH_GLANCE_DB_USER }}
  glance-db-password: {{ AUTH_GLANCE_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: glance-keystone
  namespace: os-glance
type: Opaque
data:
  glance-keystone-user: {{ AUTH_GLANCE_KEYSTONE_USER }}
  glance-keystone-password: {{ AUTH_GLANCE_KEYSTONE_PASSWORD }}
