apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: glance-db
  name: glance-db
  namespace: os-glance
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3310
    protocol: TCP
    targetPort: 3310
  selector:
    openstack-app: glance-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: glance
  name: glance
  namespace: os-glance
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 9292
    protocol: TCP
    targetPort: 9292
  selector:
    openstack-app: glance
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: glance-reg
  name: glance-registry
  namespace: os-glance
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 9191
    protocol: TCP
    targetPort: 9191
  selector:
    openstack-app: glance-reg
