kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    openstack-app: api-db
  name: os-api-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/harbor/api/mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    openstack-app: api-db
  name: os-api-db
  namespace: os-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: api-manager
    version: v0.1.0
  name: api-manager
  namespace: os-api
spec:
  template:
    metadata:
      labels:
        openstack-app: api-manager
        version: v0.1.0
      name: api-manager
      namespace: os-api
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: api-manager
          image: {{ IMAGE_API_MANAGER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: os-config-kubecfg
              mountPath: /var/run/harbor/secrets/config-kubecfg
              readOnly: true
            - name: os-config-user-ipa
              mountPath: /var/run/harbor/secrets/config-user-ipa
              readOnly: true
            - name: os-config-host-ipa
              mountPath: /var/run/harbor/secrets/config-host-ipa
              readOnly: true
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
            - name: os-config-keystone-admin-user
              mountPath: /var/run/harbor/secrets/config-keystone-admin-user
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config-kubecfg
          secret:
            secretName: api-kubecfg
        - name: os-config-user-ipa
          secret:
            secretName: api-user-ipa
        - name: os-config-host-ipa
          secret:
            secretName: api-host-ipa
        - name: os-config-db-root
          secret:
            secretName: api-db-root
        - name: os-config-db
          secret:
            secretName: api-db
        - name: os-config-ssl-secret
          secret:
            secretName: api-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: api-user-ssl-secret
        - name: os-config-keystone-admin-user
          secret:
            secretName: keystone-admin-user
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: api-db
    version: v0.1.0
  name: api-db
  namespace: os-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: api-db
        version: v0.1.0
      name: api-db
      namespace: os-api
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: api-db
          image: {{ IMAGE_MARIADB_SERVER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: 3310
              hostPort: 3310
              protocol: TCP
              name: mysql
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: DB_PORT
              value: '3310'
            - name: DB_TLS
              value: /run/harbor/auth/db
            - name: DB_ROOT_PASSWORD
              value: AUTH_API_DB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: AUTH_API_MARIADB_DATABASE
            - name: MARIADB_USER
              value: AUTH_API_MARIADB_USER
            - name: MARIADB_PASSWORD
              value: AUTH_API_MARIADB_PASSWORD
            - name: DB_NAME
              value: AUTH_API_DB_NAME
            - name: DB_USER
              value: AUTH_API_DB_USER
            - name: DB_PASSWORD
              value: AUTH_API_DB_PASSWORD
          volumeMounts:
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-db-ssl-secret
              mountPath: /run/harbor/auth/db
              readOnly: true
            - mountPath: /var/lib/mysql
              name: os-api-db
              readOnly: false
      volumes:
        - name: os-config-db-root
          secret:
            secretName: api-db-root
        - name: os-config-db
          secret:
            secretName: api-db
        - name: os-config-db-ssl-secret
          secret:
            secretName: api-db-ssl-secret
        - name: os-api-db
          persistentVolumeClaim:
            claimName: os-api-db
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: api
    version: v0.1.0
  name: horizon-api-master
  namespace: os-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: api
        version: v0.1.0
      name: horizon-api-master
      namespace: os-api
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: horizon-api
          image: {{ IMAGE_API_API }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: 4433
              hostPort: 4433
              protocol: TCP
              name: https
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: false
      volumes:
        - name: os-config-db
          secret:
            secretName: api-db
        - name: os-config-ssl-secret
          secret:
            secretName: api-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: api-user-ssl-secret
