# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# api-ssl-secret - from marina service manager
# api-user-ssl-secret - from marina service manager
# api-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: api-kubecfg
  namespace: os-api
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-user-ipa
  namespace: os-api
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-host-ipa
  namespace: os-api
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-db-root
  namespace: os-api
type: Opaque
data:
  mariadb-root-password: {{ AUTH_API_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-db
  namespace: os-api
type: Opaque
data:
  mariadb-test-database: {{ AUTH_API_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_API_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_API_MARIADB_PASSWORD }}
  api-db-name: {{ AUTH_API_DB_NAME }}
  api-db-user: {{ AUTH_API_DB_USER }}
  api-db-password: {{ AUTH_API_DB_PASSWORD }}
