apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: api-db
  name: api-db
  namespace: os-api
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    openstack-app: api-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: api
  name: api
  namespace: os-api
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 443
    protocol: TCP
    targetPort: 4433
  selector:
    openstack-app: api
