# Additional secrets required by this namespace:
# ovn-ssl-secret - from marina service manager
# ovn-user-ssl-secret - from marina service manager
# ovn-northbound-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: ovn-kubecfg
  namespace: os-ovn
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
