apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: ovn-node
  name: ovn
  namespace: os-ovn
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 6640
    targetPort: 6640
    protocol: TCP
    name: ovsdb
  selector:
    openstack-app: ovn-node
