# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# heat-ssl-secret - from marina service manager
# heat-user-ssl-secret - from marina service manager
# heat-db-ssl-secret - from marina service manager
# heat-cloudwatch-ssl-secret
# heat-cfn-ssl-secret
apiVersion: v1
kind: Secret
metadata:
  name: heat-kubecfg
  namespace: os-heat
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: heat-user-ipa
  namespace: os-heat
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: heat-host-ipa
  namespace: os-heat
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: heat-db-root
  namespace: os-heat
type: Opaque
data:
  mariadb-root-password: {{ AUTH_HEAT_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: heat-db
  namespace: os-heat
type: Opaque
data:
  mariadb-test-database: {{ AUTH_HEAT_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_HEAT_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_HEAT_MARIADB_PASSWORD }}
  heat-db-name: {{ AUTH_HEAT_DB_NAME }}
  heat-db-user: {{ AUTH_HEAT_DB_USER }}
  heat-db-password: {{ AUTH_HEAT_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: heat-keystone
  namespace: os-heat
type: Opaque
data:
  heat-keystone-user: {{ AUTH_HEAT_KEYSTONE_USER }}
  heat-keystone-password: {{ AUTH_HEAT_KEYSTONE_PASSWORD }}
