apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: marina
    version: v0.1.0
  name: marina-update
  namespace: os-marina
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: marina
        version: v0.1.0
      name: marina
      namespace: os-marina
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: mandracchio-repo
          image: {{ IMAGE_MARINA_RPMOSTREE }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: DEVICE
              value: lo
            - name: PORT
              value: 8081
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          securityContext:
            privileged: false
