apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: os-marina
  name: marina
  namespace: os-marina
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    openstack-app: marina-update
