apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: messaging
    version: v0.1.0
  name: messaging
  namespace: os-messaging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: messaging
        version: v0.1.0
      name: messaging
      namespace: os-messaging
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: messaging-api
          image: {{ IMAGE_RABBITMQ_SERVER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: 5672
              hostPort: 5672
              protocol: TCP
              name: rabbit
            - containerPort: 25672
              hostPort: 25672
              protocol: TCP
              name: rmq-dist
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: RABBIT_PORT
              value: '5672'
            - name: RABBIT_NODENAME
              value: messaging
            - name: RABBIT_TLS
              value: /run/harbor/auth/ssl
            - name: RABBIT_USER
              value: AUTH_MESSAGING_USER
            - name: RABBIT_PASS
              value: AUTH_MESSAGING_PASS
          volumeMounts:
            - name: os-config-messaging-auth
              mountPath: /var/run/harbor/secrets/config-messaging-auth
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
          securityContext:
            privileged: false
      volumes:
        - name: os-config-messaging-auth
          secret:
            secretName: messaging-auth
        - name: os-config-ssl-secret
          secret:
            secretName: messaging-ssl-secret
