apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: messaging
  name: messaging
  namespace: os-messaging
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    openstack-app: messaging
