apiVersion: v1
kind: Pod
metadata:
  labels:
    harbor-app: marina-services
    version: v0.1.0
  name: marina-services
  namespace: marina
spec:
  hostNetwork: true
  containers:
  - name: marina-services
    image: {{ IMAGE_MARINA_MASTER }}
    imagePullPolicy: {{ IMAGE_PULL_POLICY }}
    volumeMounts:
      - mountPath: /etc/harbor
        name: harbor-config
      - mountPath: /var/run/docker.sock
        name: docker-socket
  volumes:
    - name: harbor-config
      hostPath:
        path: /etc/harbor
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
