apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-kubecfg
  namespace: os-ipsilon
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-user-ipa
  namespace: os-ipsilon
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-host-ipa
  namespace: os-ipsilon
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-root-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-root-db-name: {{ AUTH_IPSILON_DB_ROOT_NAME }}
  ipsilon-root-db-user: {{ AUTH_IPSILON_DB_ROOT_USER }}
  ipsilon-root-db-password: {{ AUTH_IPSILON_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-db-name: {{ AUTH_IPSILON_DB_NAME }}
  ipsilon-db-user: {{ AUTH_IPSILON_DB_USER }}
  ipsilon-db-password: {{ AUTH_IPSILON_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-admin-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-admin-db-name: {{ AUTH_IPSILON_ADMIN_DB_NAME }}
  ipsilon-admin-db-user: {{ AUTH_IPSILON_ADMIN_DB_USER }}
  ipsilon-admin-db-password: {{ AUTH_IPSILON_ADMIN_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-users-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-users-db-name: {{ AUTH_IPSILON_USERS_DB_NAME }}
  ipsilon-users-db-user: {{ AUTH_IPSILON_USERS_DB_USER }}
  ipsilon-users-db-password: {{ AUTH_IPSILON_USERS_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-trans-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-trans-db-name: {{ AUTH_IPSILON_TRANS_DB_NAME }}
  ipsilon-trans-db-user: {{ AUTH_IPSILON_TRANS_DB_USER }}
  ipsilon-trans-db-password: {{ AUTH_IPSILON_TRANS_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-samlsession-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-samlsession-db-name: {{ AUTH_IPSILON_SAMLSESSION_DB_NAME }}
  ipsilon-samlsession-db-user: {{ AUTH_IPSILON_SAMLSESSION_DB_USER }}
  ipsilon-samlsession-db-password: {{ AUTH_IPSILON_SAMLSESSION_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-saml2session-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-saml2session-db-name: {{ AUTH_IPSILON_SAML2SESSION_DB_NAME }}
  ipsilon-saml2session-db-user: {{ AUTH_IPSILON_SAML2SESSION_DB_USER }}
  ipsilon-saml2session-db-password: {{ AUTH_IPSILON_SAML2SESSION_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-openid-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-openid-db-name: {{ AUTH_IPSILON_OPENID_DB_NAME }}
  ipsilon-openid-db-user: {{ AUTH_IPSILON_OPENID_DB_USER }}
  ipsilon-openid-db-password: {{ AUTH_IPSILON_OPENID_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipsilon-openidc-db
  namespace: os-ipsilon
type: Opaque
data:
  ipsilon-openidc-db-name: {{ AUTH_IPSILON_OPENIDC_DB_NAME }}
  ipsilon-openidc-db-user: {{ AUTH_IPSILON_OPENIDC_DB_USER }}
  ipsilon-openidc-db-password: {{ AUTH_IPSILON_OPENIDC_DB_PASSWORD }}
