# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# nova-ssl-secret - from marina service manager
# nova-user-ssl-secret - from marina service manager
# nova-db-ssl-secret - from marina service manager
# metadata-ssl-secret - from marina service manager
# serial-ssl-secret - from marina service manager
# spice-ssl-secret - from marina service manager
# vnc-ssl-secret - from marina service manager
# neutron-shared-secret - from os-neutron namespace defs
apiVersion: v1
kind: Secret
metadata:
  name: nova-kubecfg
  namespace: os-nova
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-user-ipa
  namespace: os-nova
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-host-ipa
  namespace: os-nova
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-db-root
  namespace: os-nova
type: Opaque
data:
  mariadb-root-password: {{ AUTH_NOVA_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-db
  namespace: os-nova
type: Opaque
data:
  mariadb-test-database: {{ AUTH_NOVA_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_NOVA_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_NOVA_MARIADB_PASSWORD }}
  nova-db-name: {{ AUTH_NOVA_DB_NAME }}
  nova-db-user: {{ AUTH_NOVA_DB_USER }}
  nova-db-password: {{ AUTH_NOVA_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-keystone
  namespace: os-nova
type: Opaque
data:
  nova-keystone-user: {{ AUTH_NOVA_KEYSTONE_USER }}
  nova-keystone-password: {{ AUTH_NOVA_KEYSTONE_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-api-db
  namespace: os-nova
type: Opaque
data:
  nova-api-db-name: {{ AUTH_NOVA_API_DB_NAME }}
  nova-api-db-user: {{ AUTH_NOVA_API_DB_USER }}
  nova-api-db-password: {{ AUTH_NOVA_API_DB_PASSWORD }}
