apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova-db
  name: nova-db
  namespace: os-nova
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3312
    protocol: TCP
    targetPort: 3312
  selector:
    openstack-app: nova-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova
  name: nova
  namespace: os-nova
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 8774
    protocol: TCP
    targetPort: 8774
  selector:
    openstack-app: nova
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova-serialproxy
  name: serial
  namespace: os-nova
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 6083
    protocol: TCP
    targetPort: 6083
  selector:
    openstack-app: nova-serialproxy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: nova-api-metadata
  name: metadata
  namespace: os-nova
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 8775
    protocol: TCP
    targetPort: 8775
  selector:
    openstack-app: nova-api-metadata
