# flexvolume-user-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: flexvolume-keystone
  namespace: kube-system
type: Opaque
data:
  kuryr-keystone-user: {{ AUTH_FLEXVOLUME_KEYSTONE_USER }}
  kuryr-keystone-password: {{ AUTH_FLEXVOLUME_KEYSTONE_PASSWORD }}
