# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# portal-ssl-secret - from marina service manager
# portal-user-ssl-secret - from marina service manager
# portal-keytab-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: portal-kubecfg
  namespace: os-portal
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-user-ipa
  namespace: os-portal
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-host-ipa
  namespace: os-portal
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-email
  namespace: os-portal
type: Opaque
data:
  smtp-host: {{ AUTH_PORTAL_SMTP_HOST }}
  smtp-port: {{ AUTH_PORTAL_SMTP_PORT }}
  smtp-user: {{ AUTH_PORTAL_SMTP_USER }}
  smtp-pass: {{ AUTH_PORTAL_SMTP_PASS }}
  email-addr-from: {{ AUTH_PORTAL_DEFAULT_FROM_EMAIL }}
  email-addr-admin: {{ AUTH_PORTAL_DEFAULT_ADMIN_EMAIL }}
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-keystone
  namespace: os-portal
type: Opaque
data:
  neutron-keystone-user: {{ AUTH_PORTAL_KEYSTONE_USER }}
  neutron-keystone-password: {{ AUTH_PORTAL_KEYSTONE_PASSWORD }}
