apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: portal
  name: portal
  namespace: os-portal
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 4434
    protocol: TCP
    targetPort: 4434
  selector:
    openstack-app: portal
